# Generated by Django 5.0 on 2024-09-21 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskflow', '0004_alter_project_owner_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 10, 21)),
        ),
    ]
