# Generated by Django 5.0 on 2024-09-22 04:08

import datetime
import taskflow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskflow', '0008_remove_file_name_remove_file_uploaded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_files/', validators=[taskflow.models.validate_csv])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 10, 22)),
        ),
    ]
